name: Run Node.js Script Every 5 Minutes

on:
  # Schedule the workflow to run every 5 minutes
  schedule:
    - cron: '*/5 * * * *'  # This will run the workflow every 5 minutes

  # Trigger the workflow on push events (e.g., new commits)
  push:
    branches:
      - main  # or specify the branch you want to track

  # Allow manual  triggering of the workflow from the GitHub Actions tab
  workflow_dispatch:

jobs:
  run-node-script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the repository
      uses: actions/checkout@v3  # Updated to version 3 of actions/checkout

    - name: Set up Node.js
      uses: actions/setup-node@v3  # Updated to v3
      with:
        node-version: '18'  # Use a Node.js version greater than 18 (e.g., 18 or higher)

    - name: Install dependencies
      run: npm install

    - name: Run the Node.js script
      run: node test.js  # Adjust the path to your Node.js script
